### ISSUE TITLE
Broken install on alpine docker

### ISSUE THREAD

**Issue by DaniloZZZ** [deepmipt/DeepPavlov#1067]
Using this Dockerfile, deeppavlov installes, but the installation seems to be broken

```
from python:3.7-alpine
run apk add g++ python3-dev git make cmake

# Use wheels, because building scipy from source is a pain. https://github.com/pypa/pip/issues/3969
run echo "manylinux1_compatible = True" >> /usr/local/lib/python3.7/_manylinux.py
run pip3 install deeppavlov
run python3 -c "from deeppavlov import train_model"

```
I get error on last command
`ImportError: cannot import name 'train_model' from 'deeppavlov' (/usr/local/lib/python3.7/site-packages/deeppavlov/__init__.py)`

**Comment by litinsky** [comment]
Hi! Thanks for the info. Yes, we discovered problems with DeepPavlov on Alpine and started investigating solution. If you need to build some solution with DeepPavlov on Docker, you can try one of our pre-buillt Docker images: https://hub.docker.com/r/deeppavlov/base-cpu

**Comment by praneethgb** [comment]
Hi @litinsky, Are Deeppavlov on Alpine problems resolved now?.

**Comment by IgnatovFedor** [comment]
Hi, @DaniloZZZ 
The problem was with numpy in Alpine image: `Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so)`. This error was muted by DeepPavlov, that's why only `cannot import name 'train_model' from 'deeppavlov'` occured. We have prepared a bug concealment fix for DeepPavlov, but can't fix usage of numpy installed via pip in Alpine.
