### ISSUE TITLE
 ImportError: cannot import name 'build_model'

### ISSUE THREAD

**Issue by SahithiParsi** [deepmipt/DeepPavlov#1189]
Hi team,

I have installed DeepPavlov version 0.1.0 but unable to import build_model. PFA screenshot for details.
Configuration: Windows 10

![image](https://user-images.githubusercontent.com/16195067/80368774-e2da5a00-88aa-11ea-9626-fd8703297131.png)

**Comment by IgnatovFedor** [comment]
Hi, @SahithiParsi 
Please, send result of the following code:
import deeppavlov
print(deeppavlov.__version__, deeppavlov.__file__)

**Comment by SahithiParsi** [comment]
![image](https://user-images.githubusercontent.com/16195067/80372070-8b3eed00-88b0-11ea-923c-c7658aaafe34.png)

**Comment by IgnatovFedor** [comment]
@SahithiParsi, could you also send result of `deeppavlov.__dir__()`?

**Comment by IgnatovFedor** [comment]
@SahithiParsi, we found out what caused this error. Some libraries in your virtual environment was installed with errors, so import error was raised when you imported deeppavlov. Original import error was muted by our library, that's why you can import deeppavlov without any errors. Error occured after initialization of deeppavlov.configs, that's why `ImportError: cannot import name "build_model"` error was raised but configs was imported successfully, although they are declared in one file.
We prepared fix for error hiding issue in DeepPavlov. Now you can edit `C:\\Users\sahithi\Anaconda3\lib\site-packages\deeppavlov\__init__.py` like in this commit: https://github.com/deepmipt/DeepPavlov/pull/1200/commits/98cc69f9cbc44ea10561a5a1a7bb019f4aadf4bd (although it’s better to use `sys.stderr` instead of `sys.stdout`). After these changes you can see which library is imported incorrectly.
