### ISSUE TITLE
Multi-Lingual Sentence Embedding 

### ISSUE THREAD

**Issue by ashispapu** [deepmipt/DeepPavlov#1194]
Can someone help me to get an example of multi-lingual sentence embedding? I want to extract the sentence embedding for Hindi using the Multi-lingual sentence embedding model.

Thanks.

**Comment by paulagd** [comment]
Hi, I have the same problem. I have seen that in the go_bot tutorial they use glove embeddings by downloading them and passing them to the embedder like:

`        download_resource(url="http://files.deeppavlov.ai/embeddings/glove.6B.100d.txt",
                      dest_paths=[bot_path])

         gobot_config['chainer']['pipe'][-1]['embedder'] = {
        "class_name": "glove",
        "load_path": os.path.join(bot_path, 'glove.6B.100d.txt')
    }`

However,  I would like to use Spanish embeddings because my dataset is in Spanish but I am not able to know where are they allocated. I have tried to access "http://files.deeppavlov.ai/embeddings/" but it does not work as a link, so I do not know where to look for those pre-trained embeddings.

**Comment by ashispapu** [comment]
@PaGul Check if below url helps you for the embeddings. I 'm trying to find a way to use the Multi-ligual sentence embedding for Hindi. Let me know if you find anything useful.

http://docs.deeppavlov.ai/en/master/features/pretrained_vectors.html

**Comment by yoptar** [comment]
Hi, @ashispapu,

You can find an example of getting embeddings using Bert in our documentation: http://docs.deeppavlov.ai/en/master/features/models/bert.html#bert-as-embedder

There is also a configuration for getting only sentence-level embeddings: https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/embedder/bert_sentence_embedder.json
you can use it like so:
```python3
from deeppavlov import build_model, configs

m = build_model(configs.embedder.bert_sentence_embedder, download=True)

texts = ['Hi, i want my embedding.', 'And mine too, please!']
sent_max_embs, sent_mean_embs, bert_pooler_outputs = m(texts)
```

**Comment by ashispapu** [comment]
Thanks @yoptar
