### ISSUE TITLE
tarfile.ReadError

### ISSUE THREAD

**Issue by alissiawells** [deepmipt/DeepPavlov#1253]
My module, based on deeppavlov, runs on my machine. However, it does not work on a remote server with Ubuntu 18.04 because of  tarfile.ReadError.
![515DD10E-2DE1-453D-BFD5-4C0DA4AFD67C](https://user-images.githubusercontent.com/35057128/85176100-aeb76000-b281-11ea-97e7-b0b74810a5d8.jpeg)

I use deeppavlov of 0.8.0 version with small modifications: github.com/alissiawells/deeppavlov (treshold instead of model’s verdict in the output)

**Comment by yoptar** [comment]
Hi @alissiawells,

This is most likely related to #1109 (it will be fixed in the next release) as the console shows 2.76 KB downloaded while the file itself is about 5 MB.
There may be a typo in the download link or some troubles with network.

You can try and download and extract the file with other methods.
