### ISSUE TITLE
NER Model training with own Datasets

### ISSUE THREAD

**Issue by veeri** [deepmipt/DeepPavlov#1271]
I am trying to train **ner_ontonotes_bert** mode for NER with below code 

````
from deeppavlov import configs, train_model
from deeppavlov.core.commands.utils import parse_config

config_dict = parse_config(configs.ner.ner_ontonotes_bert)
config_dict['dataset_reader']['data_path'] = "DATASET_PATH"

ner_model = train_model(configs.ner.ner_ontonotes_bert)
````
```
my DATASET is like this
What	O
are	O
places	B-Place
visit	O
Tamilnadu	O
?	O
which	O
places	B-Place
famous	I-Interest
```

for tourism chat bot
my Question is with existing ner_ontonotes_bert model, they used intent names like Person, Cardinal, Date manually in Code 
If we want use DeepPalvol with Our Datasets like above, how we can do 
can anyone suggest me please

**Comment by veeri** [comment]
@DeepPavlov  can you suggest something related to above issue

**Comment by theanhle** [comment]
Hi @veeri,

There is no problem with training on a new dataset since the output tags are directly collected by reading through all the training file. This is done by using a preprocessing class named `simple_vocab`. Please check [the config file](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert.json) for more details.
