### ISSUE TITLE
Support Cuda 11 

### ISSUE THREAD

**Issue by lizush23** [deepmipt/DeepPavlov#1511]
Hi,
I am trying to Run NER model on A100. 
I get CUBLAS_STATUS_ALLOC_FAILED error.
Is it something to do with CUDA ? 
A100 supports CUDA 11 - do you have a docker image compatible with CUDA 11?
Thanks

**Comment by max1mka1** [comment]
The same question. I tried to build Dockerfile using "nvcr.io/nvidia/tensorflow:20.06-tf1-py3" image, which is pre-compiled for CUDA 11 version tensorflow 1.15.2
(https://developer.nvidia.com/blog/accelerating-tensorflow-on-a100-gpus/)

I also installed deeppavlov with --no-deps argument because the library install tensorflow1.15 for CUDA 10 version.

But it does not worked.

Can DeepPavlov Library run in inference with GPU on RTX3090 using tensorflow?

**Comment by IgnatovFedor** [comment]
Hi.

To work with newer CUDA versions please use our pytorch-based models. In the future release 1.0.0 all TF-based models will be removed/replaced with python-based ones. 1.0.0rc0 pre-release is already [available](https://github.com/deepmipt/DeepPavlov/releases/tag/1.0.0rc0).
