### ISSUE TITLE
building go-bot in russian

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#375]
Hi!
I want to build a go-bot using DeepPavlov in russian.
The task of gobot is to output phone number of requested employee by his name, surname, fathers name.
I plan to use tutorial03 as a reference.
And the main idea is using instead of DSTC2 data set a new one, which i gonna generate in DSTC2 format.
Has the described aproach a right to exist?

**Comment by vikmary** [comment]
Hi! TLTR: yes, it has.

I suggest firstly to try `configs/go_bot/gobot_dstc2.json` without `intent_classifier` (set it to `null`, because i guess your data would be small.
And then try to add `intent_classifier` and `embedder` (you should provide russian embeddings yourself though).

 To integrate a database of employee names, you  should provide dataset with appropriate `db_result` fields and run `python -m deeppavlov train configs/go_bot/database_dstc2.json` (with little config fixes). And then you would be able to use the database for training `configs/go_bot/gobot_dstc2.json`. See [docs](https://docs.deeppavlov.ai) for details.

If your dialogs are simple (as it seems to me), then the model shouldn't require too much data to be properly trained. DSTC2 was trained on 1000 dialogs, you will need less. I guess 100 will be even enough, but you'll have to check by yourself.

**Comment by vitalyuf** [comment]
Thank you!

**Comment by vitalyuf** [comment]
HI!
As I understand editing of configs is not enough.
First I should provide labeled russian datasets for training NER and slotfilling components.
Then I have to train these components using provided data.
And after this I can build a go-bot.
Or correct me please if I'm wrong.

BTW: Should I open new issues in such cases or I may reopen elder ones if i get some corellated troubles in future?

**Comment by vitalyuf** [comment]
Oh. I see.
I can use configs/ner/slotfill_dstc2_raw.json as slotfilling component with previously prepared dictionary at slotfill_raw component. In this case I don't need NER component.
Am I right?

**Comment by vitalyuf** [comment]
Oh. I see now.
I can use configs/ner/slotfill_dstc2_raw.json as slotfilling component with previously prepared dictionary at slotfill_raw component.
In this case I don't need NER component.

**Comment by vikmary** [comment]
Welcome back, @vitalyuf !
In order to train go_bot model, you should beforehand train a NER model (if you have a ner model, you have a slot filler model too).
Yeah, you should provide a dataset for training NER model, or can have your dialogs labelled with entities (for slot-filler) and intents (for classifier). You can also try our [pretrained]() for russian model.

**Comment by vikmary** [comment]
Yes, if you want a minimal slot-filler, you can use configs/ner/slotfiller_dstc2_raw.json, which will match slots according to your dictionary using Levenshtein distance.

**Comment by vikmary** [comment]
I guess, reopening the issue is the right way =)

**Comment by mu-arkhipov** [comment]
In order to use simple pattern matching slot_filler you need to build a vocabulary of slots and slot values pairs with paraphrases. You can find an example of such vocabulary [here](http://lnsigo.mipt.ru/export/datasets/dstc_slot_vals.json).  You need to specify path to this file in `slotfill_raw` part of the `slotfill_dstc2_raw.json` config file.

**Comment by vitalyuf** [comment]
Thanks, I've alreay tried raw filler. And it works. I plan to generate such a dictionary from a list of all possible surnames and names. I suggest the resulting file will be about  30Mb size.
Also I tried to use ner_rus.json as a subcomponent of slotfill_dstc2 with reference to my stc_slot_vals.json but it failed (`KeyError: 'PER' at ---> 65         for entity_name in self._slot_vals[slot]: `of `~/projects/DP/DeepPavlov/deeppavlov/models/slotfill/slotfill.py in ner2slot(self, input_entity, slot)`).
Maybe output of ner_rus and input of dstc_slotfilling components have different formats or dstc_slotfilling is not intended for russian lang?

Generally speaking for now I want to fill 'name', 'surname', 'fathersname' slots.
Maybe using of ner_rus before applying slotfiller have no sense in this case?

**Comment by vitalyuf** [comment]
Unfortunately, raw slotfiller IRL performs not very good for my task due to next reasons:
- using large dictionary of surnames (~13Mb) by slotfiller is very slow (~15 sec delay for getting answer);
- often slotfiller changes initial token to any of nearest tokens ('Иванов'->'Живанов' for example).

**Comment by mu-arkhipov** [comment]
It is not suited for large vocabularies. For large vocabularies prefix trees would be way faster. Furthermore, we will explore the 'Иванов'->'Живанов' case.

**Comment by vitalyuf** [comment]
Hi!
For my gobot (phone reference) I have an idea to train ner model using your ner_dstc2.json.
I prepared dstc2-???.jsonlist -files and slot_vals.gson file.
But when I launch `python -m deeppavlov train ./ner_rus.json`  a new version of slot_vals is always downloaded.
How to disable this option (of downloading this file)?

**Comment by mu-arkhipov** [comment]
We will fix it next release. However, you can try to fix it via removing a couple of lines here https://github.com/deepmipt/DeepPavlov/blob/e91ff6c3eafbd49b6f09499d2e1b4b5675b513bb/deeppavlov/models/slotfill/slotfill.py#L115.

**Comment by vitalyuf** [comment]
Hi!
Thanks, but the problem was at deeppavlov/dataset_iterators/dstc2_ner_iterator.py (def _build_slot_vals(slot_vals_json_path='data/'):)

**Comment by vitalyuf** [comment]
Hi!
I trained a NER component (based on yours one for DSTC2) for recognizing names and surnames by context.
Then I include a path to NER-config file into slotfilling config-file (base on yours one forn DSTC2).
Then I train slotfilling component.
And then I include slotfilling component in edited gobot_dstc2_full.json condif file and train-evaluate this component.
But **at inference mode** I see that slotfilling component is **trying to find** a value tagged by NER component **at** **its slot_vals.json** dictionary.
But my surnames and names could not be included into a dictionary, because there is no list of all possible surnames and names.
Please tell me if there is a way for slotfiller not to search values in its dictionary.

**Comment by kshurik** [comment]
@vitalyuf Hi. Did you find pre-trained embeddings for Russian language in .txt format?
