### ISSUE TITLE
how do i fine tune automatically when i add new data

### ISSUE THREAD

**Issue by kkpriyankacoding** [deepmipt/DeepPavlov#485]
is there any approach to evaluate hyper para meters i tried evolution of deeppavlov it took 5 days still not yet completed please suggest a solution

Thanks,
In Advance

**Comment by dilyararimovna** [comment]
Hello!
Parameters evolution description can be found [here](https://deeppavlov.readthedocs.io/en/latest/intro/hypersearch.html#parameters-evolution-for-deeppavlov-models). Please, look at parameter `iterations`. If you did not assign iterations number, you will run an infinite number of iterations.

**Comment by SekharDhana** [comment]
hi,
i tried giving 5 or 10 iterations for evolution process, it is iterating only 5 or 10 times only, but the accuracy is very very less, then i went for paramsearch as well if i give n folds its iterating till n number if i give leave one out cross validation (loo) it is iterating infinetly but still i am not able to get good accuracy can you help me so that i could get best accuracy.
