### ISSUE TITLE
building skill-managers (agents)

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#612]
Hi!
I have some questions.
1.
If there is a **tutorial** or something similar which **explains** how to build a dialog system based on several skills and an **agent**?
2.
Is the **purpose of the agent component** to build skill managers?
Or is its purpose for ambiguity of several dialogs tracking ('Thai' example)?

3.
If I do:
```
model = build_model(configs.go_bot.gobot_dstc2, download=True)
skill = DefaultStatelessSkill(model)
agent = DefaultAgent([skill], skills_selector=HighestConfidenceSelector())

```
It works OK.
But I add one more skill then agent doesn't work well. It takes first skill from the skills list for answering.

Should a model output a confidence along with y_predicted?

4.
If so could you explain please how to update a json-config to train apropriate model (with y_prdicted and confidence at output)?

**Comment by vikmary** [comment]
1. There is only a basic tutorial about skills and an agent: http://docs.deeppavlov.ai/en/master/intro/hello_bot.html
2. Yes, Agent is the one purposed to handle ambiguity of tracking several dialog states.
3. Confidence returned by DefaultStatelessSkill is always equal to 1.0 .
4. You should look at [eCommerce Bot config](https://github.com/deepmipt/DeepPavlov/blob/0.1.0/deeppavlov/configs/ecommerce_skill/bleu_retrieve.json), it is a skill already. You can rewrite (gobot_dstc2.json)[https://github.com/deepmipt/DeepPavlov/blob/0.1.0/deeppavlov/configs/go_bot/gobot_dstc2.json] so that the whole pipeline outputs three values: `response`, `confidence` and `state`. `state` can be empty as `go_bot` component handles state already (that is also why one instance of `go_bot` can handle only one user at a time, call `model.reset()` to reset it's dialog state). `confidence` though should be calculated based on network output probabilities of classes (for example, rewrite https://github.com/deepmipt/DeepPavlov/blob/0.1.0/deeppavlov/models/go_bot/network.py#L127 so that it outputs predicted label AND probability associated with predicted label.

**Comment by vitalyuf** [comment]
Thank you!
Suppose I have more than one skill (or model).
What is the right way to build a dialogue manager in this case?
(by the term "dialogue manager", I mean an entry point, something like yandex.alice has: one tells an activation phrase and the subsequent dialogue takes place with the selected skill)
Should I develop my own skill manager or DeepPavlov has solutions for building such dialogue managers?
Maybe DeepPavlov's agents are able to solve this task?

**Comment by yoptar** [comment]
You can add a [Filter](http://docs.deeppavlov.ai/en/master/_modules/deeppavlov/core/agent/filter.html#Filter) to your agent.
A `skills_filter` decides utterance which skills to run for every utterance and a `skills_selector` selects for every utterance only one reply from selected skills.
So you can add a filter that will enable one skill for batch elements where `history` is empty and another where it's not.
You can take a look at the [TransparentFilter](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/agents/filters/transparent_filter.py) class as an example.

**Comment by vitalyuf** [comment]
Thank you!
