### ISSUE TITLE
mismatching tokenizers

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#672]
Hi!
My go_bot differs from dstc2, but as i see this problem may occure at dstc2 go_bot.
For simplicity I will describe situation in dstc2 go_bot terms. 

At dstc2 go_got.json there is a parameter "tokenizer" of go_bot component (not a tokenizer at pipeline).
the class of this tokenizator is "stream_spacy_tokenizer".
But dstc_ner is trained using "lazy tokenizer".
It results in such cases:
if i give a string 'дай мне телефон Чулпан-Хаматовой' to a trained ner component it assumes 'Чулпан-Хаматовой' as one token.
But when i give the same string to go_bot then it divides 'Чулпан-Хаматовой' into to tokens: 'Чулпан' and 'Хаматовой'.
Maybe it is better to use one tokenizer at ner and at go_bot?

**Comment by vikmary** [comment]
Hi!

The problem you are describing is not that important for DSTC2, because the data is already tokenized. Thus during training DSTC2 all components will try to tokenize the text one more time (with different tokenizers), but will result in approximately the same tokens.

During inference slot_filler component is already receiving tokens from go_bot. So no problem with it too.
https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/go_bot/network.py#L285

It will somehow work for DSTC2, but will fail for a dataset without preliminary tokenization.

Thanks, will make the fix.
