### ISSUE TITLE
Which operating systems are supported?

### ISSUE THREAD

**Issue by Dobatymo** [deepmipt/DeepPavlov#70]
I just tried to install DeepPavlov on Windows and it fails due to `pyfasttext` requiring `cysignals` (which is not available for windows).
I could not find any mention about what operating systems are supported.
So is Windows supported in theory and just breaks because of that dependency, or was it never intended to be supported at all?

**Comment by seliverstov** [comment]
Hi,
currently, we do not support Windows and our main supported platform is Linux.
We do not focus on Windows mainly because some dependencies don't support Windows at all (like pyfasttext) or they have complicated setup process. In theory, some components of our library, that do not depend on pyfasttext, can be run on Windows.
