### ISSUE TITLE
Bert_Squad context length longer than 512 tokens sequences

### ISSUE THREAD

**Issue by Chunglwc** [deepmipt/DeepPavlov#896]
Hi,

Currently I have a long context and the answer cannot be extracted from the context when the context exceeds a certain length. Is there any python code to deal with long length context.

P.S. I am using BERT-based model for context question answering.

**Comment by Chunglwc** [comment]
I am desperate for the solution.

**Comment by vikmary** [comment]
Hi,
It would be difficult to support longer context.
The problem is BERT uses positional embeddings, therefore an individual embedding for each position is learnt (1st, 2nd, ... 512th). To use longer context you have to somehow initialize embeddings for positions after 512th. Possible way might be to train those, but thus you will require data with long sequences.
You can try to initialize all the embeddings after 512th with, for example, 512th embedding. But there is no proof for the concept.
