### ISSUE TITLE
Using ranking module with pretreined bert for prediction

### ISSUE THREAD

**Issue by norbertryc** [deepmipt/DeepPavlov#927]
How can I use pretrained on ubuntu dataset bert (representation based) model from ranking module in the following scenario: I have list of possible responses (in file) and I would like to load pretrained model in python and get ordering of possible responses for given context? My goal is to define function rank(possible_answers, context, model) which gives the ordering (not responses but numbers representing the ordering - list of numbers in which each number show position of respective possible response).

**Comment by elenaermakova** [comment]
The simplest way to do it is to use config file 
```
deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_sep.json
```
First, you need to install all required packages
```
python -m deeppavlov install deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_sep.json`
```
Import some components
```
from deeppavlov.core.commands.utils import parse_config
from deeppavlov import build_model
```
And build the model using config file
```
path_to_config = 'deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_sep.json'
config = parse_config(path_to_config)
#this line is used in order not to download ubuntu dataset
config['metadata']['download'] = config['metadata']['download'][1:] 
model = build_model(config, download=True)
```
Now you can get predictions. 
The input should be a list of lists where the first element represents a context and the rest of elements represent response candidates. In case of one sample you can use just a list (as in the example below) instead of list of lists.
```
logits = model(['context', 'response_1', 'response_2'])
#the output looks like [[logit_1, logit_2]]
```
To get ordering you can run this
```
ordering = np.flip(np.argsort(logits, -1), -1)
```
