### ISSUE TITLE
Training function without config

### ISSUE THREAD

**Issue by dilyararimovna** [deepmipt/DeepPavlov#934]
Hello!

Function `train_evaluate_model_from_config` works fine but sometimes one wants to train some pipeline without config. 
I still do not understand how to build it except the following way:
1. build class pipeline which have `__call__`, `train_on_batch` or `fit`, `save` and `load` methods.
2. send this class instance to some `train_pipeline` function given additional training parameters (such as number of epochs, metrics etc).

Maybe you will find out how to build in other way.
Thank you in advance.

**Comment by grwlf** [comment]
Hi. To my knowledge, it is not currently possible to replace config alltogether since Chainer component depends on it in many ways.

We think that for some tasks this design may be too complex, so we tried to limit the role of config in a pipeline. The repo below contains our results:

https://github.com/Huawei-MRC-OSI/mrc-osi-dp-public

We replaced `train_evaluate_model_from_config` with a couple of short hand-written functions which operate config as a json object. We found that if we remove all branches which are unnesesary for particular task, we get rather short code. In particular, at line 167 [1] we see config as a Python JSON object. In theory, you could build this config from scratch here rather than read it from file.

[1] - https://github.com/Huawei-MRC-OSI/mrc-osi-dp-public/blob/ec8367c17ea044855ea06c99e60bad046b1f1afb/mironov/dptest/StandaloneBERT.py#L167
